stages:
  - test

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip python3-pytest
    - apt-get install -y python-dev python-pip python-pytest
    - python3 -m pip install -e ./
    - python3 -m pytest
    - python2 -m pip install -e ./
    - python2 -m pytest
