stages:
  - test

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip python3-pytest
    - python3 -m pip install -e ./
    - python3 -m pytest -sv --doctest-modules
